services:
  backend:
    image: openjdk:25-ea-4-jdk-oraclelinux9
    ports:
      - "8080:8080"
    env_file:
      - secret.env
    depends_on:
      - auth_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth_db:5432/authDB
    volumes:
      - ./target:/app
      - ./logs:/logs
    command: [ "java", "-jar", "/app/auth-0.0.1-SNAPSHOT.jar" ]

  auth_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: authDB
    ports:
      - "5432:5432"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yaml
      - ./logs:/logs
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
